name: Build PyInstaller binaries

on:
  push:
    tags: [ "v*" ]          # release tag
  workflow_dispatch:        # manual trigger

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: windows-latest
            out_name: mrc2movie-windows.exe
          - os: ubuntu-latest
            out_name: mrc2movie-linux
    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install project + PyInstaller
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller .
        shell: bash

      # ---- build one-file binary ----
      - name: PyInstaller (one-file)
        run: |
          pyinstaller --onefile \
                      --name mrc2movie \
                      src/mrc2movie/cli.py   # <-- adjust entry point
        shell: bash

      # ---- rename for clarity ----
      - name: Rename artefact
        run: mv dist/mrc2movie* dist/${{ matrix.out_name }}
        shell: bash

      # ---- upload so other jobs can see it ----
      - name: Upload artefact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.out_name }}
          path: dist/${{ matrix.out_name }}

  # ----------------------------------------------------------
  # OPTIONAL: create a GitHub release and attach the binaries
  # ----------------------------------------------------------
  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download artefacts
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true

      - name: Make Linux binary executable
        run: chmod +x mrc2movie-linux

      - name: Create / update release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: |
            mrc2movie-windows.exe
            mrc2movie-linux